# Generated by Django 3.0.2 on 2020-02-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_Admin',
            field=models.NullBooleanField(),
        ),
    ]
